file(GLOB CDF_TEST_SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/test_*.c")

foreach(test_src ${CDF_TEST_SOURCES})
    get_filename_component(test_name ${test_src} NAME_WE)
    add_executable(${test_name} ${test_src})
    target_link_libraries(${test_name} PRIVATE cdf_static cdf_warnings)
    target_compile_options(${test_name} PRIVATE -fsanitize=address,undefined -g -O0)
    target_link_options(${test_name} PRIVATE -fsanitize=address,undefined)
    add_test(NAME ${test_name} COMMAND ${test_name})
endforeach()
